### ISSUE TITLE
[REQUEST] Away mode activation and deactication?

### ISSUE THREAD

**Issue by Hedda** [jordanruthe/homeassistant-phyn-backup#1]
Reqeust control to enable and disable ”away mode”.

FYI, @rsocko has implemented away mode in his forks of aiophyn and homeassistant-phyn here:

https://github.com/rsocko/homeassistant-phyn/commits/set_away_mode

https://github.com/rsocko/aiophyn

Also @opq8 has pulled in that in his fork too:

**Comment by jordanruthe** [comment]
As I get time my intent is to add this functionality in.

**Comment by jordanruthe** [comment]
This is now complete. I apologize, but this wasn't a proper fork so I changed repositories to make it a fork of MizterB's
